---
- name: web server installation
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    dversion: "{{ 'centos' if ansible_distribution == 'CentOS'
                  else 'ubuntu' if ansible_distribution == 'Ubuntu'
                  else 'centos' }}"
  tasks:
    - name: webserver install
      include_tasks: "{{ dversion }}.yaml"
