# -*- mode: ruby -*-
# vi: set ft=ruby :

##### ANSIBLE NODE #####
Vagrant.configure("2") do |config|
  config.vm.define "node1" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "node1"
    cfg.vm.network :public_network, type: "bridge", dev: "br0", mode: "bridge", network_name: "public", ip: "211.183.3.201"
    cfg.vm.network "private_network", ip: "172.16.1.201" 
    cfg.vm.network "forwarded_port", guest: 22, host: 60001, auto_correct: true, id: "ssh"
    cfg.vm.provision "file", source: "pkey.txt", destination: "pkey.txt"
    cfg.vm.provision "shell", inline: "cat pkey.txt >> /home/vagrant/.ssh/authorized_keys"
    cfg.vm.provision "shell", inline: "systemctl restart sshd"
  end
  config.vm.define "node2" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "node2"
    cfg.vm.network :public_network, type: "bridge", dev: "br0", mode: "bridge", network_name: "public", ip: "211.183.3.202"
    cfg.vm.network "private_network", ip: "172.16.1.202"
    cfg.vm.network "forwarded_port", guest: 22, host: 60002, auto_correct: true, id: "ssh"
    cfg.vm.provision "file", source: "pkey.txt", destination: "pkey.txt"
    cfg.vm.provision "shell", inline: "cat pkey.txt >> /home/vagrant/.ssh/authorized_keys"
    cfg.vm.provision "shell", inline: "systemctl restart sshd"
  end
  config.vm.define "node3" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "node3"
    cfg.vm.network :public_network, type: "bridge", dev: "br0", mode: "bridge", network_name: "public", ip: "211.183.3.203"
    cfg.vm.network "private_network", ip: "172.16.1.203"
    cfg.vm.network "forwarded_port", guest: 22, host: 60003, auto_correct: true, id: "ssh"
    cfg.vm.provision "file", source: "pkey.txt", destination: "pkey.txt"
    cfg.vm.provision "shell", inline: "cat pkey.txt >> /home/vagrant/.ssh/authorized_keys"
    cfg.vm.provision "shell", inline: "systemctl restart sshd"
  end
  config.vm.define "server" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "server"
    cfg.vm.network :public_network, type: "bridge", dev: "br0", mode: "bridge", network_name: "public", ip: "211.183.3.200"
    cfg.vm.network "private_network", ip: "172.16.1.200"
    cfg.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
    cfg.vm.provider :libvirt do |resource|
      resource.memory = 2048
      resource.cpus = 2
    end
    cfg.vm.provision "shell", inline: "yum -y install epel-release && yum -y install ansible vim curl wget"
  end
end
