---
- name: test configuration
  hosts: localhost
  gather_facts: no

  tasks:
    - name: install git
      yum:
        name: git
        state: present

    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: creating index.html
      get_url: url=https://www.naver.com dest=/var/www/html/index.html
